version: "3"
services:
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        networks:
            - historical-events-net

    historical-events:
        build:
            context: ../
            dockerfile: ./go-services/historical-events/Dockerfile
        ports:
            - "8080:8080"
            - "9999:9999"
        restart: always
        depends_on:
            - mongo
        env_file: .envs/historical-events.env
        networks:
            - historical-events-net

networks:
    historical-events-net:
